- name: Download and install ddns-cloudflare
  unarchive:
    src: "https://github.com/kshcherban/ddns-cloudflare/releases/download/v{{ ddns_cloudflare_version }}/ddns-cloudflare-linux-{{ (ansible_machine == 'aarch64') | ternary('arm64', 'amd64') }}.tar.gz"
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes
    creates: /usr/local/bin/ddns-cloudflare-{{ ddns_cloudflare_version }}
    owner: root
    group: root

- name: Create ddns-cloudflare symlink
  file:
    srs: /usr/local/bin/ddns-cloudflare-{{ ddns_cloudflare_version }}
    dest: /usr/local/bin/ddns-cloudflare
    state: link
    force: yes

- name: Setup ddns-cloudflare cron
  cron:
    name: ddns-cloudflare
    minute: "{{ ddns_cloudflare_schedule }}"
    user: root
    job: "API_TOKEN={{ ddns_cloudflare_token }} DOMAIN={{ ddns_cloudflare_domain }} /usr/local/bin/ddns-cloudflare >> {{ ddns_cloudflare_log }} 2>&1"

- name: Rotate ddns-cloudflare log
  blockinfile:
    path: "/etc/logrotate.d/ddns-cloudflare"
    create: yes
    owner: root
    group: root
    block: |
        {{ ddns_cloudflare_log }} {
               weekly
               rotate 3
               size 10M
               compress
               delaycompress
        }
